### ISSUE TITLE
Another question about the data

### ISSUE THREAD

**Issue by wzm2256** [tomato1mule/edf#2]
Hi again, I am trying to generate more data using your script, for example I want to use different mug models. I am using `generate_demo.py` from the `iclr2023_rebuttal_ver` branch. However, I always run into errors 
``
Traceback (most recent call last):
  File "/home/server/Codetest/edf/generate_demo.py", line 177, in <module>
    raise TimeoutError('couldn\'t find IK solution')
TimeoutError: couldn't find IK solution
``
Do you have any idea how this can be avoided? Thanks!

By the way, I modify line
`` task.reset(seed = seed, mug_pose=cup_pose, mug_type='default', distractor=False, use_support=False)``
to 
`` task.reset(seed = seed, mug_pose=cup_pose, mug_type='cups', distractor=False, use_support=False)``
to use different mug model, and I run
``python generate_demo.py --file-name='mug_task_rim.gzip' --pick-type='rim' ``

**Comment by wzm2256** [comment]
I managed to get some demos on cup 0,1,4,6,9,10 by tuning the seeds, but I still can not get demos on other cups. Anyway, that should be enough for me now. Thanks!

**Comment by tomato1mule** [comment]
Yes, it is because the IK solver cannot find a feasible joint configuration for the demonstrated target pose.
I didn't made an exception handling for this issue because for the default mug instances, the solution can be found.
You may manually adjust the seeds so that only successful seeds are used.

By the way, the demonstration oracle is intended to be only used for the train instances (default mug/bowl/bottles).
I am not sure how it would behave with test instances (unseen mugs/bowls/bottles) but it is very likely that the oracle would fail.
Please be aware of this fact when generating your own samples.

Thank you for your interest in our project!
